language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements.txt
script: nosetests --with-coverage --cover-package=graphite_influxdb
notifications:
  email:
    on_failure: change
