language: python
python:
  - 2.6
  - 2.7
env:
  - INFLUXDB_VERSION=0.9.2-rc1
before_install:
  - wget https://s3.amazonaws.com/influxdb/influxdb_${INFLUXDB_VERSION}_amd64.deb
  - sudo dpkg -i influxdb_${INFLUXDB_VERSION}_amd64.deb
  - sudo /etc/init.d/influxdb start
  - sleep 5
  - curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE graphite"
  - now=`date +%s`
  - half_hour_ago=$(echo "${now}-1800" | bc -l)
  - curl -XPOST 'http://localhost:8086/write?db=graphite' --data-binary "integration_test value=3 ${half_hour_ago}010000000"
  - curl -XPOST 'http://localhost:8086/write?db=graphite' --data-binary "integration_test value=3 ${now}010000000"
install:
  - pip install -r requirements.txt
  - pip install coverage
script: nosetests --with-coverage --cover-package=graphite_influxdb
notifications:
  email:
    on_failure: change
